apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build-push
  namespace: demo-app
spec:
  description: Docker 이미지 빌드 및 푸시
  params:
    - name: image-name
      description: Docker 이미지 이름
      type: string
  workspaces:
    - name: source
      description: 소스코드 workspace
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)
        - --destination=$(params.image-name)
        - --cache=true
        - --verbosity=info
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: docker-hub-secret