apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
  namespace: demo-app
spec:
  description: Maven을 사용하여 Spring Boot 애플리케이션 빌드
  workspaces:
    - name: source
      description: 소스코드 workspace
  steps:
    - name: build
      image: maven:3.8.6-openjdk-17
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        echo "Maven 빌드 시작..."
        mvn clean package -DskipTests
        echo "빌드 완료!"
        ls -la target/